<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>friday_manipulation</name>
  <version>0.1.0</version>
  <description>One-shot manipulation command examples for Friday.</description>
  <maintainer email="opensource@holiday-robotics.com">Holiday Robotics Open Source</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>friday_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>tf2_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
