uint8 mode
---
uint16 RESULT_SUCCESS=0
uint16 RESULT_INVALID_ARGUMENT=1
uint16 RESULT_NOT_READY=2
uint16 RESULT_BUSY=3
uint16 RESULT_TIMEOUT=4
uint16 RESULT_HARDWARE_ERROR=5
uint16 RESULT_PERMISSION_DENIED=6
uint16 RESULT_INTERNAL_ERROR=255

bool success
uint16 result_code
string<=128 message
